### ISSUE TITLE
No such config: Base

### ISSUE THREAD

**Issue by bsenkus** [brianmc95/OpenCV2X#15]
Hi,
I am having trouble running the sample simulation. I performed all the steps as stated in the document, but when I use the run_simulte-cars command, I get an error saying

>  <!> No such config: Base

![resim](https://user-images.githubusercontent.com/70312277/93319866-12b5da00-f819-11ea-950d-a622ddc00a47.png)

I tried running with both Clion and
`cmake --build build --target run_simulte-cars`
but I couldn't figure out how to solve this problem.

What would be the reason? 

Thanks in advance.

**Comment by brianmc95** [comment]
Hi @bsenkus,

Apologies this is my mistake I have changed the names of the configurations and have left out a base configuration which is the default that is attempted to be run. You have two ways around this issue the first is to rename the first configuration in the `scenarios/cars/omnetpp.ini` file which is named `[Config highwayFast]` to instead read as `[Config Base]` or else you can change the configuration you want to run you can do this by opening the terminal in the `build` folder for OpenCV2X which you have already setup and using `ccmake` or `cmake-gui` to update cmake to point at the correct configuration which is done by updating the `SCENARIO_CONFIG` parameter to `highwayFast` and that should get it running for you. I will take note of this and update to ensure this mistake doesn't persist into the next version and update the documentation to explain how to change configurations as well. 

Thanks for highlighting this and hope it gets you up and running, any questions then feel free to get back to me.

**Comment by bsenkus** [comment]
@brianmc95 thank you very much for your help and quick reply. The issue has been solved.

**Comment by divakar5** [comment]
Hi Sir,

I'm facing the same issue while triggering "cmake --build build --target run_simulte-cars". I didn't understand the solutions you have posted above. I tried the first solution by changing Config highwayFast to Config Base but still the same issue. could you please tell me how to overcome this issue? your help will be much appreciated.

![Opencv2x simulation error](https://user-images.githubusercontent.com/80413167/111188587-3779e700-85db-11eb-8bc4-1edb38bbeeea.PNG)

**Comment by xxxxxy211** [comment]
Before you can fully build the system you need to ensure that the WITH_SIMULTE option is set in cmake. This is done in
the build directory by using cmake-gui or ccmake if that is installed.  
so you need use cmake-gui or ccmake to ensure WITH_SIMULTE is set!
